<?php
/** @noinspection PhpUndefinedVariableInspection */
/** @var CDS\DataModels\Contact $company */
$company = $arguments['company'];
/** @var CDS\DataModels\Contact $contact */
$contact = $arguments['contact'];

 ?>
<div class="container">
    <div class="col-8 offset-2">
        <h2 class="text-center"><?= $company->CompanyName; ?> - <?= $contact->getContactName(); ?></h2>
        <form action="/" method="post">
            <div class="form-group">
                <div class="row">
                    <label class="col-2" for="title">Title</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->Title; ?>" name="title" class="col-10 form-control" id="title">
                </div>
                <div class="row">
                    <label class="col-2" for="fname">First Name</label>
                    <input disabled type="text" maxlength="50" value="<?= $contact->FName; ?>" name="fname" class="col-10 form-control" id="fname">
                </div>
                <div class="row">
                    <label class="col-2" for="mname">Middle Name</label>
                    <input disabled type="text" maxlength="50" value="<?= $contact->MName; ?>" name="mname" class="col-10 form-control" id="mname">
                </div>
                <div class="row">
                    <label class="col-2" for="lname">Last Name</label>
                    <input disabled type="text" maxlength="50" value="<?= $contact->LName; ?>" name="lname" class="col-10 form-control" id="lname">
                </div>
                
                <div class="row">
                    <label class="col-2" for="suffix">Suffix</label>
                    <input disabled type="text" maxlength="50" value="<?= $contact->Suffix; ?>" name="suffix" class="col-10 form-control" id="suffix">
                </div>
                <div class="row">
                    <label class="col-2" for="address1">Address 1</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->Address_1; ?>" name="address1" class="col-10 form-control" id="address1">
                </div>
                <div class="row">
                    <label class="col-2" for="address2">Address 2</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->Address_2; ?>" name="address2" class="col-10 form-control" id="address2">
                </div>
                <div class="row">
                    <label class="col-2" for="city">City</label>
                    <input disabled type="text" maxlength="50" value="<?= $contact->City; ?>" name="city" class="col-10 form-control" id="city">
                </div>
                <div class="row">
                    <label class="col-2" for="state">State</label>
                    <input disabled type="text" maxlength="5" value="<?= $contact->State; ?>" name="state" class="col-10 form-control" id="state">
                </div>
                <div class="row">
                    <label class="col-2" for="postal">Postal Code</label>
                    <input disabled type="text" maxlength="24" value="<?= $contact->PostalCode; ?>" name="postal" class="col-10 form-control" id="postal">
                </div>
                <div class="row">
                    <label class="col-2" for="website">Website</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->Website; ?>" name="website" class="col-10 form-control" id="website">
                </div>
                <div class="row">
                    <label class="col-2" for="primaryemail">Primary Email</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->Email_Primary; ?>" name="primaryemail" class="col-10 form-control" id="primaryemail">
                </div>
                <div class="row">
                    <label class="col-2" for="email2">Email 2</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->Email_2; ?>" name="email2" class="col-10 form-control" id="email2">
                </div>
                <div class="row">
                    <label class="col-2" for="email3">Email 3</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->Email_3; ?>" name="email3" class="col-10 form-control" id="email3">
                </div>
                <div class="row">
                    <label class="col-2" for="email4">Email 4</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->Email_4; ?>" name="email4" class="col-10 form-control" id="email4">
                </div>
                <div class="row">
                    <label class="col-2" for="primaryphone">Primary Phone</label>
                    <input disabled type="text" maxlength="10" value="<?= $contact->Phone_Primary; ?>" name="primaryphone" class="col-10 form-control" id="primaryphone">
                </div>
                <div class="row">
                    <label class="col-2" for="mobilephone">Mobile Phone</label>
                    <input disabled type="text" maxlength="10" value="<?= $contact->Phone_Mobile; ?>" name="mobilephone" class="col-10 form-control" id="mobilephone">
                </div>
                <div class="row">
                    <label class="col-2" for="landlinephone">Landline Phone</label>
                    <input disabled type="text" maxlength="10" value="<?= $contact->Phone_Land; ?>" name="landlinephone" class="col-10 form-control" id="landlinephone">
                </div>
                <div class="row">
                    <label class="col-2" for="fax">Fax</label>
                    <input disabled type="text" maxlength="10" value="<?= $contact->Phone_Fax; ?>" name="fax" class="col-10 form-control" id="fax">
                </div>
                <div class="row">
                    <label class="col-2" for="twitter">Twitter Handle</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->TwitterHandle; ?>" name="twitter" class="col-10 form-control" id="twitter">
                </div>
                <div class="row">
                    <label class="col-2" for="facebook">Facebook Name</label>
                    <input disabled type="text" maxlength="255" value="<?= $contact->FaceBookName; ?>" name="facebook" class="col-10 form-control" id="facebook">
                </div>
                <div class="form-check">
                    <input disabled type="checkbox" class="form-check-input" id="active" name="active" <?php if ( $contact->Active ): ?>checked="checked"<?php endif; ?>>
                    <label class="form-check-label" for="active">Active</label>
                </div>
                <div class="form-check">
                    <input disabled disabled type="checkbox" class="form-check-input" id="deleted" name="deleted" <?php if ( $contact->Deleted ): ?>checked="checked"<?php endif; ?>>
                    <label class="form-check-label" for="deleted">Deleted</label>
                </div>
                <div class="form-check">
                    <input disabled disabled type="checkbox" class="form-check-input" id="archived" name="archived" <?php if ( $contact->Archived ): ?>checked="checked"<?php endif; ?>>
                    <label class="form-check-label" for="archived">Archived</label>
                </div>
				<a href="/editContact.php?company=<?= $company->PRI; ?>&contact=<?= $contact->PRI; ?>">Edit Contact</a> |
                <a href="/contacts.php?company=<?= $company->PRI; ?>">View Contact List</a><br />
                <a href="/companies.php?company=<?= $company->PRI; ?>">View Company</a> | <a href="/contactHistory.php?company=<?= $company->PRI; ?>&contact=<?= $contact->PRI; ?>">See History</a>
            </div>
        
        </form>
    </div>
</div>
