<?php
/** @noinspection PhpUndefinedVariableInspection */
/** @var CDS\DataModels\Company $company */
$company = $arguments['company'];
/** @var array $contactHistory */
$contactHistory = $arguments['contactHistory'];
/** @var Contact $contact */
$contact = $arguments['contact'];

use CDS\DataModels\Contact; ?>
<div class="container">
	<div class="col-8 offset-2">
		<h2 class="text-center"><i>History</i> - <?= $company->CompanyName; ?> - <?= $contact->getContactName(); ?></h2>
		<form action="/" method="post">
			<div class="form-group">
                <?php /** @var CDS\DataModels\ContactHistory $history */ ?>
                <?php foreach ($contactHistory as $history): ?>
					<div class="row mt-4">Edited by: <?= $history->user->Username; ?></div>
					<div class="row">Edited on: <?= $history->Timestamp->format('m/d/Y h:i:s A'); ?></div>
					<div class="row">
						<div class="col-3">Name</div>
						<div class="col-4">Old Value</div>
						<div class="col-4">New Value</div>
					</div>
                    <?php foreach ($history->New as $key => $val): ?>
                        <?php if ($history->Old->$key === true) {
                            $history->Old->$key = 'Y';
                        }
                        if ($history->Old->$key === false) {
                            $history->Old->$key = 'N';
                        }
                        if ($history->New->$key === true) {
                            $history->New->$key = 'Y';
                        }
                        if ($history->New->$key === false) {
                            $history->New->$key = 'N';
                        } ?>
						<div class="row">
							<div class="col-3">
                                <?= preg_replace('/(?<! )[A-Z]/', ' $0', str_replace('_', ' ', $key)); ?>
							</div>
							<div class="col-4"><input type="text" class="form-control" readonly
													  value="<?= $history->Old->$key; ?>"></div>
							<div class="col-4"><input type="text" class="form-control" readonly
													  value="<?= $history->New->$key; ?>"></div>
						</div>
                    
                    <?php endforeach; ?>
                <?php endforeach; ?>
				<a href="/contacts.php?company=<?= $company->PRI; ?>&contact=<?= $contact->PRI; ?>">View Contact Details</a> | <a href="/editContact.php?company=<?= $company->PRI; ?>&contact=<?= $contact->PRI; ?>">Edit Contact</a>
			</div>

		</form>
	</div>
</div>
