<div class="container">
	<div class="col-lg-6 col-12 offset-lg-3 mt-5 pt-5">
		<h1 class="text-center mb-4">Login</h1>
		<div class="card bg-middle card-login px-5 py-5">
			<div class="card-body">
				<form action="/index.php" method="post">
					<div class="form-group">
						<label class="col-4" for="login-username">Username</label>
						<input type="text" id="login-username" name="username">
					</div>
					<div class="form-group">
						<label class="col-4" for="login-password">Password</label>
						<input type="password" id="login-password" name="password">
					</div>


					<button type="submit" name="submit" class="my-3 btn btn-info btn-block" id="login_submit">Login
					</button>
                    <?php if (!empty($arguments['loginFailed'])): ?>
						<p class="alert alert-danger text-center fade show">Invalid Username/Password</p>
                    <?php endif; ?>
				</form>
			</div>
		</div>

	</div>
</div>